--init.lua is our previous main.lua

control_dead = dref.getDataref("sim/operation/override/override_control_surfaces")
trim_value = dref.getDataref("sim/flightmodel2/controls/elevator_trim")
dref.setAutoPublish( true )
charge = dref.getDataref("sim/cockpit/electrical/battery_charge_watt_hr")
dref.setFloatV( charge, 1, 1 )
starter_switch = dref.newInt("ujs/control/starter_switch")
dref.setInt( starter_switch, 1 )
control_fuel = dref.newInt("ujs/control/fuel_tank")
is_crank_on = dref.newInt("ujs/control/crank_on")
fire_door = dref.newInt("ujs/control/fire_door")
strainer_time = dref.newFloat("ujs/control/strainer_time")
our_oil = dref.newFloat("ujs/control/oil_qty")
xdr_oilquan = dref.getDataref("sim/flightmodel/engine/ENGN_oil_quan")-- This is the master branch. Holds all idexes
oil_actual = dref.getFloatV(xdr_oilquan, 1, 1 )--we pick which one we want here!
oil_pool = dref.newFloat("ujs/control/oil_pool")
fire_door_smooth = dref.newFloat("ujs/control/fire_door_smooth")
warmup_fail = dref.newInt("ujs/control/warm_fail")
warmup_consequence = dref.getDataref("sim/operation/failures/rel_airres0")
engine_is_hydrolocked = dref.newInt("ujs/control/engn_hydrolocked")
engine_can_lock = dref.newInt("ujs/control/engn_can_lock")
rod_is_bent = dref.newInt("ujs/control/rod_bent")
engine_is_broken = dref.newInt("ujs/control/engine_is_broken")
oil_pressure_fail = dref.getDataref("sim/operation/failures/rel_oilpmp0")
new_oil_set = dref.newInt("ujs/control/new_oil_set")
burn_baby = dref.getDataref("sim/operation/failures/rel_engfir0")
disparo = dref.getDataref("sim/operation/failures/rel_pshaft0")
prop_strike = dref.getDataref("sim/operation/failures/rel_engsep0")
fire_partner = dref.getDataref("sim/operation/failures/rel_engfai0")
auto_preflight = dref.newInt("ujs/control/auto_preflight")
disable_truevintage = dref.newInt("ujs/control/disable_truevintage")
my_age = dref.newInt("ujs/control/trueage")
pissing = dref.newInt("ujs/control/pissing")
pitot_cover = dref.newInt("ujs/control/pitot_cover")
engine_covers = dref.newInt("ujs/control/engine_covers")
chocks_on = dref.newInt("ujs/control/chocks_on")
pitot_blocked = dref.getDataref("sim/operation/failures/rel_pitot")
has_stall = dref.getDataref("sim/aircraft/view/acf_has_stallwarn")
is_stalling = dref.getDataref("sim/cockpit2/annunciators/stall_warning_ratio")
chocks_brake = dref.getDataref("sim/flightmodel/controls/parkbrake")
clock_inner_timer = dref.newFloat("ujs/control/inner_timer")
clock_seconds = dref.newInt("ujs/control/clock_seconds")
clock_minutes = dref.newFloat("ujs/control/clock_minutes")
clock_hours = dref.newFloat("ujs/control/clock_hours")
winding_left = dref.newInt("ujs/control/winding_left")
dref.setInt(winding_left, 691200)
clock_mode = dref.newInt("ujs/control/clock_mode")
clock_tuning = dref.newInt("ujs/control/clock_tuning")
rewinding = dref.newInt("ujs/control/rewinding")
xdr_gearstat = dref.getDataref("sim/aircraft/parts/acf_gearstatdef")
gdown1 = dref.getDataref("sim/cockpit2/controls/gear_handle_down")
gdown2 = dref.getIntV(xdr_gearstat,5,1)
gdown3 = dref.getIntV(xdr_gearstat,6,1)
height = dref.getDataref("sim/flightmodel/position/y_agl")
is_prop = dref.newInt("ujs/control/is_prop")
show_fake_crank = dref.newInt("ujs/control/show_fake_crank")
trinco1 = dref.newInt("ujs/control/trinco1")
trinco1_smooth = dref.newFloat("ujs/control/trinco1_smooth")
trinco2 = dref.newInt("ujs/control/trinco2")
trinco2_smooth = dref.newFloat("ujs/control/trinco2_smooth")
can_bug = dref.newInt("ujs/control/can_bug")
override_brakes = dref.getDataref("sim/operation/override/override_toe_brakes")
left_toe_brakes = dref.getDataref("sim/cockpit2/controls/left_brake_ratio")
right_toe_brakes = dref.getDataref("sim/cockpit2/controls/right_brake_ratio")
brake_gates = dref.newInt("ujs/control/brake_gates")
xdr_throttle_ratio = dref.getDataref("sim/cockpit2/engine/actuators/throttle_ratio")
throttle_ratio = dref.getFloatV(xdr_throttle_ratio,1, 1) 
oil_temp = dref.newFloat("ujs/control/oil_temp")
crank_deg = dref.newFloat("ujs/control/crank/crank_deg")
control_lock = dref.newFloat("ujs/control/control_lock")
wobble = dref.newFloat("ujs/control/wobble")
can_prime = dref.newInt ("ujs/control/can_prime")
primed = dref.newInt ("ujs/control/primed")
xdr_starter_actual = dref.getDataref("sim/cockpit2/engine/actuators/ignition_on")
starter_actual = dref.getIntV(xdr_starter_actual, 1, 1)
bat_on = dref.getDataref("sim/cockpit/electrical/battery_on")
xdr_ignite = dref.getDataref("sim/cockpit2/engine/actuators/ignition_key")
ignite = dref.getIntV(xdr_ignite, 1, 1)
fire = dref.newInt("ujs/control/fire")
trigger = dref.newInt("ujs/control/trigger")
crank_travel = dref.newFloat("ujs/control/crank/crank_travel")
actual_fuel_tank = dref.getDataref("sim/cockpit2/fuel/fuel_tank_selector")
can_pump = dref.newInt("ujs/control/wobble_can_pump")
pumped = dref.newInt("ujs/control/wobble_pumped")
wobble_psi = dref.newFloat("ujs/control/wobble_psi")
wobble_ok = dref.newInt("ujs/control/wobble_ok")
xdr_tail_lock_ratio = dref.getDataref("sim/multiplayer/controls/tail_lock_ratio")
tail_lock_ratio = dref.getFloatV(xdr_tail_lock_ratio, 1,1)
on_ground = dref.getDataref("sim/flightmodel/failures/onground_any")
xdr_tailwheel_contact = dref.getDataref("sim/flightmodel2/gear/on_ground")
tailwheel_contact = dref.getIntV(xdr_tailwheel_contact, 1, 1)
tailwheel_scraping = dref.newInt("ujs/control/tailwheel_scraping")
IAS = dref.getDataref("sim/flightmodel/position/true_airspeed")
rolling_flat = dref.newInt("ujs/control/rolling_flat")
xdr_mixture_ratio = dref.getDataref("sim/cockpit2/engine/actuators/mixture_ratio")
--mixture_ratio = xp.getFloatV("sim/cockpit2/engine/actuators/mixture_ratio", 1, 1 )
mixture_ratio = dref.getFloatV(xdr_mixture_ratio, 1, 1)
outside_temperature = dref.getDataref("sim/weather/temperature_ambient_c")
reduced_crank = dref.newFloat("ujs/control/reduced_crank")
--Timers
time = dref.getDataref("sim/operation/misc/frame_rate_period")
wobble_decay = dref.newFloat("ujs/control/wobble_decay")
time_to_warm = dref.newFloat("ujs/control/time_to_warm")
oil_tick = dref.newFloat("ujs/control/oil_tick")
oil_buildup = dref.newFloat("ujs/control/oil_buildup")
start_time = dref.newFloat("ujs/control/start_time")
engine_timer = dref.newFloat("ujs/control/engine_timer")
rod_animator = dref.newInt("ujs/control/rod_animator")
warm_treble = dref.newFloat("ujs/control/warm_treble")
wind_dir = dref.getDataref("sim/cockpit2/gauges/indicators/wind_heading_deg_mag")
our_heading = dref.getDataref("sim/flightmodel/position/mag_psi")
we_cooling = dref.newInt("ujs/control/we_cooling")
hide_pilots = dref.newInt("ujs/control/hide_pilots")
time_to_mini_botch = dref.newFloat("ujs/control/mini_botch_time")
--Engine Running
xdr_engine_on = dref.getDataref("sim/flightmodel/engine/ENGN_running")
engine_on = dref.getIntV(xdr_engine_on, 1, 1)
--Oil and servicing
oil_can_service = dref.newInt("ujs/control/oil_can_service")
oil_cap = dref.newFloat("ujs/control/oil_cap")
oil_lock = dref.newFloat("ujs/control/oil_lock")
oil_is_in = dref.newFloat("ujs/control/oil_is_in")
oil_is_in_smooth = dref.newFloat("ujs/control/oil_is_in_smooth")
dref.setFloat(oil_is_in, 1)
dref.setFloat(oil_is_in_smooth, 1)
dref.setFloat(oil_lock, 1)
oil_cap_smooth = dref.newFloat("ujs/control/oil_cap_smooth")
oil_travel = dref.newFloat("ujs/control/oil_travel")
servicing = dref.newInt("ujs/service/servicing")
right_cowling_on = dref.newInt("ujs/control/rco")
left_cowling_on = dref.newInt("ujs/control/lco")
dref.setInt(left_cowling_on, 1)
dref.setInt(right_cowling_on, 1)
left_cowling_can_open = dref.newInt("ujs/control/lco_can_open")
right_cowling_can_open = dref.newInt("ujs/control/rco_can_open")
oil_in_line = dref.newFloat("ujs/control/oil_in_line")
oil_in_line_can_burp = dref.newInt("ujs/control/oil_can_burp")
oil_in_line_burps =  dref.newInt("ujs/control/oil_burps")
altimeter_failed = dref.getDataref("sim/operation/failures/rel_g_alt")
--CHEGUEI ATE AQUI. O PROXIMO É OIL CAN BUILD!!!
oil_can_build = dref.newInt("ujs/control/oil_can_build")
oil_15 = dref.newInt("ujs/control/15")
oil_14 = dref.newInt("ujs/control/14")
oil_13 = dref.newInt("ujs/control/13")
oil_12 =  dref.newInt("ujs/control/12")
oil_11 = dref.newInt("ujs/control/11")
oil_10 = dref.newInt("ujs/control/10")
oil_9 = dref.newInt("ujs/control/9")
oil_8 = dref.newInt("ujs/control/8")
oil_7 = dref.newInt("ujs/control/7")
oil_6 = dref.newInt("ujs/control/6")
oil_5 = dref.newInt("ujs/control/5")
oil_4 = dref.newInt("ujs/control/4")
--Instruments

oil_press = dref.newFloat("ujs/control/oil_press")
xdr_oil_temp_actual = dref.getDataref("sim/flightmodel/engine/ENGN_oil_temp_c")
oil_temp_actual = dref.getFloatV(xdr_oil_temp_actual, 1, 1)
xdr_oil_press_actual = dref.getDataref("sim/flightmodel/engine/ENGN_oil_press_psi")
oil_press_actual = dref.getFloatV(xdr_oil_press_actual, 1, 1)
yoke_deflection = dref.getDataref("sim/cockpit2/controls/yoke_pitch_ratio")
yoke_roll = dref.getDataref("sim/cockpit2/controls/yoke_roll_ratio")
yoke_can_lock = dref.newInt("ujs/control/yoke_can_lock")
yoke_is_locked = dref.newInt("ujs/control/yoke_is_locked")
xdr_primer_ratio = dref.getDataref("sim/cockpit2/engine/actuators/primer_ratio")
primer_ratio = dref.getFloatV(xdr_primer_ratio, 1, 1)
primer_smooth = dref.newInt("ujs/control/primer_smooth")
primer_cock = dref.newInt("ujs/control/primer_cock")
xdr_actual_tail_deg = dref.getDataref("sim/flightmodel2/gear/tire_steer_actual_deg")
actual_tail_deg = dref.getFloatV(xdr_actual_tail_deg, 1, 1)
primer_cock_smooth = dref.newFloat("ujs/control/primer_cock_smooth")

extinguish = dref.newInt("ujs/control/extinguish")
--------------Warmup and Failures
is_warm = dref.newInt("ujs/control/is_warm")
xdr_RPM = dref.getDataref("sim/cockpit2/engine/indicators/engine_speed_rpm") 
RPM = dref.getFloatV(xdr_RPM, 1, 1)
warmup_can_fail = dref.newInt("ujs/control/warm_can_fail")
crank_me = dref.newInt("ujs/control/crank_me")
engine_broken_consequence = dref.getDataref("sim/operation/failures/rel_seize_0")
xdr_strainer_fail = dref.getDataref("sim/flightmodel/failures/prop_ice_per_engine")
strainer_fail = dref.getFloatV(xdr_strainer_fail, 1, 1)
prime_time = dref.newInt("ujs/control/prime_timer")
throttle_can_pump = dref.newInt("ujs/control/throttle_can_pump")
throttle_pumped = dref.newInt("ujs/control/throttle_pumped")
--Startup Sequence
start_runmode = dref.newInt("ujs/control/runmode")
s1 = dref.newInt("ujs/control/start1")
s2 = dref.newInt("ujs/control/start2")
s3 = dref.newInt("ujs/control/start3")
s4 = dref.newInt("ujs/control/start4")
s5 = dref.newInt("ujs/control/start5")
s6 = dref.newInt("ujs/control/start6")
s7 = dref.newInt("ujs/control/start7")
s8 = dref.newInt("ujs/control/start8")
s9 = dref.newInt("ujs/control/start9")
smoking = dref.newInt("ujs/control/smokey")
botched = dref.newInt("ujs/control/botched")
botched_fail = dref.getDataref("sim/operation/failures/rel_engfai0")
time_to_botch = dref.newFloat("ujs/control/botch_time")

mini_botch = dref.newInt("ujs/control/mini_botch")
mini_botch_partner = dref.getDataref("sim/operation/failures/rel_fuepmp0")
mini_botch_partner2 = dref.getDataref("sim/operation/failures/rel_ele_fuepmp0")
--3D Menu
can_menu = dref.newInt("ujs/control/can_menu")
go_menu = dref.newInt("ujs/control/go_menu")
menu = dref.newInt("ujs/control/menu")
go_back = dref.newInt("ujs/control/go_back")
close = dref.newInt("ujs/control/close")
engine_repaired = dref.newInt("ujs/control/engine_repaired")
oil_filled = dref.newInt("ujs/control/oil_filled")
airframe_overhauled = dref.newInt("ujs/control/airframe_overhauled")
strainer_repaired = dref.newInt("ujs/control/strainer_repaired")
menu_page = dref.newInt("ujs/control/menu_page")
	--3D Menu show/hides for components
engine_show = dref.newInt("ujs/control/engine_show")
engine_status = dref.newInt("ujs/control/engine_status")
menu_engine_argument = dref.newInt("ujs/control/menu_engine_argument")
menu_argument = dref.newInt("ujs/control/menu_argument")
POH_page = dref.newInt("ujs/control/poh_page")
poh_pagemode = dref.newInt("ujs/control/pagemode")
--Call these to make actual 3D model visible. Engine status+Engine show == 1 then we set these bad guys
strainer_bad = dref.newInt("ujs/control/strainer_bad")	
strainer_caut = dref.newInt("ujs/control/strainer_caut")	
strainer_good = dref.newInt("ujs/control/strainer_good")
strainer_status = dref.newInt("ujs/control/strainer_status")
dref.setInt(strainer_status, 2)
engine_good = dref.newInt("ujs/control/engine_good")
engine_caut = dref.newInt("ujs/control/engine_caut")
engine_bad = dref.newInt("ujs/control/engine_bad")
oil_good = dref.newInt("ujs/control/oil_good")
oil_caut = dref.newInt("ujs/control/oil_caut")
oil_bad = dref.newInt("ujs/control/oil_bad")
report_fire = dref.newInt("ujs/control/report_fire")
report_disparo = dref.newInt("ujs/control/report_disparo")
report_pstrike = dref.newInt("ujs/control/report_pstrike")
report_metal = dref.newInt("ujs/control/report_metal")
report_general = dref.newInt("ujs/control/report_general")
report_hydro = dref.newInt("ujs/control/report_hydro")
report_strainer = dref.newInt("ujs/control/report_strainer")
report_seized = dref.newInt("ujs/control/report_seized")
report_bent = dref.newInt("ujs/control/report_bent")
tick_auto_preflight = dref.newInt("ujs/control/tick_preflight")
tick_auto_start = dref.newInt("ujs/control/tick_start")
tick_disable_truevintage = dref.newInt("ujs/control/tick_disable_truevintage")
tick_disable_dust = dref.newInt("ujs/control/tick_disable_dust")
    --Same as above. Cross engine status with menu visible == draw these
engn_preview_good = dref.newInt("ujs/control/engine_preview_good")
engn_preview_caut = dref.newInt("ujs/control/engine_preview_caut")
engn_preview_bad = dref.newInt("ujs/control/engine_preview_bad")
oil_preview_good = dref.newInt("ujs/control/oil_preview_good")
oil_preview_caut = dref.newInt("ujs/control/oil_preview_caut")
oil_preview_bad = dref.newInt("ujs/control/oil_preview_bad")
show_good_rods = dref.newInt("ujs/control/show_good_rods")
show_bent_rod = dref.newInt("ujs/control/show_bent_rod")
show_seized_rod = dref.newInt("ujs/control/show_seized_rod")
help_prime = dref.newInt("ujs/control/help_prime")
help_crank = dref.newInt("ujs/control/help_crank")
--
ass_show = dref.newInt("ujs/control/ass_show")
mainm_show = dref.newInt("ujs/control/mainm_show")
oil_show = dref.newInt("ujs/control/oil_show")
airframe_show = dref.newInt("ujs/control/airframe_show")
--Stuff USER CLICKED on main menu
autostart_on = dref.newInt("ujs/control/autostart_on")
disable_dust = dref.newInt("ujs/control/disable_dust")
--Pilot ShowHide Behaviour
pilot_phi = dref.getDataref("sim/graphics/view/pilots_head_phi")
pilot_the = dref.getDataref("sim/graphics/view/pilots_head_the")
pilot_psi = dref.getDataref("sim/graphics/view/pilots_head_psi")
p_x = dref.getDataref("sim/graphics/view/pilots_head_x")
p_y = dref.getDataref("sim/graphics/view/pilots_head_y")
p_z = dref.getDataref("sim/graphics/view/pilots_head_z")
x_con = dref.newInt("ujs/control/x_conflicting")
y_con = dref.newInt("ujs/control/y_conflicting")
z_con = dref.newInt("ujs/control/z_conflicting")
conflicting = dref.newInt("ujs/control/conflicting")
is_external = dref.getDataref("sim/graphics/view/view_is_external")
--vr_is_on = dref.getDataref("sim/graphics/VR/enabled")
--walkmode_on = dref.newInt("ujs/control/walkmode_on")
--Camera Shake
shake = dref.newInt("ujs/control/shake")
--------TRUE VINTAGE
new_boy = dref.newInt("ujs/control/newboy")
getting_older = dref.newInt("ujs/control/getting_older")
getting_more_older = dref.newInt("ujs/control/getting_more_older")
pretty_beaten = dref.newInt("ujs/control/pretty_beaten")
--------TRUE MECHANIC

velas_on = dref.newInt("ujs/control/velas_on")
dref.setInt(velas_on, 1)
luggage_door = dref.newInt("ujs/control/luggage_door")
luggage_can_open = dref.newInt("ujs/control/luggage_can_open")
luggage_door_smooth = dref.newFloat("ujs/control/luggage_door_smooth")
quick_external = dref.newFloat("ujs/control/quick_external")
einen_test = dref.newInt("ujs/TESTMODE/einen_test")
hydro_left = dref.newInt("ujs/control/hydro_left")
dref.setInt(hydro_left, 2000)
can_land = dref.newInt("ujs/control/can_land")
hydro_open = dref.newInt("ujs/control/hydro_open")
l_brake_fail = dref.getDataref("sim/operation/failures/rel_lbrakes")
r_brake_fail = dref.getDataref("sim/operation/failures/rel_rbrakes")
hydro_time = dref.newFloat("ujs/control/hydro_time")
low_idle = dref.getDataref("sim/aircraft2/engine/low_idle_ratio")
high_idle = dref.getDataref("sim/aircraft2/engine/high_idle_ratio")
filter_tray = dref.newFloat("ujs/control/filter_tray")
tray_cover = dref.newInt("ujs/control/tray_cover")
dref.setInt(tray_cover, 1)
oil_age = dref.newFloat("ujs/control/oil_age")
y_drain = dref.newFloat("ujs/control/y_drain")
y_drip = dref.newInt("ujs/control/y_drip")
oil_drip_bad =dref.newInt("ujs/control/odb")
oil_drip_semibad =dref.newInt("ujs/control/odsb")
oil_drip_semigood =dref.newInt("ujs/control/odsg")
oil_drip_good =dref.newInt("ujs/control/odg")
oil_filter_on = dref.newInt("ujs/control/oil_filter")
oil_filter_status = dref.newInt("ujs/control/oil_filter_status")
dref.setInt(oil_filter_status, 1500)
baffles_placed = dref.newInt("ujs/control/baffles_placed")
dref.setInt(baffles_placed, 1)
baffle_status = dref.newInt("ujs/control/baffle_status")
dref.setInt(baffle_status, 59000)
baffle_life = dref.newFloat("ujs/control/baffle_life")
dref.setFloat(baffle_life, 115200)
air_filter_status = dref.newFloat("ujs/control/air_status")
dref.setFloat(air_filter_status, 1616)
refilling_oil = dref.newInt("ujs/control/refilling_oil")
tires_serviced = dref.newInt("ujs/control/tires_serviced")
opportunist_bug = dref.newInt("ujs/control/opportunist_bug")
pbrake = dref.newFloat("ujs/control/pbrake")

rcr1 = dref.newInt("ujs/control/rcr1")
--dref.setInt(rcr1, 1)
rcr2 = dref.newInt("ujs/control/rcr2")
--dref.setInt(rcr2, 1)
rcr3 = dref.newInt("ujs/control/rcr3")
--dref.setInt(rcr3, 1)
rcr4 = dref.newInt("ujs/control/rcr4")
--dref.setInt(rcr4, 1)
--
lcr1 = dref.newInt("ujs/control/lcr1")
--dref.setInt(lcr1, 1)
lcr2 = dref.newInt("ujs/control/lcr2")
--dref.setInt(lcr2, 1)
lcr3 = dref.newInt("ujs/control/lcr3")
--dref.setInt(lcr3, 1)
lcr4 = dref.newInt("ujs/control/lcr4")
--dref.setInt(lcr4, 1)
lcr5 = dref.newInt("ujs/control/lcr5")
--dref.setInt(lcr5, 1)
lcr6 = dref.newInt("ujs/control/lcr6")
--dref.setInt(lcr6, 1)
lcr7 = dref.newInt("ujs/control/lcr7")
--dref.setInt(lcr7, 1)
lcr8 = dref.newInt("ujs/control/lcr8")
--dref.setInt(lcr8, 1)
lcr9 = dref.newInt("ujs/control/lcr9")
--dref.setInt(lcr9, 1)
left_mag_fail = dref.getDataref("sim/operation/failures/rel_magLFT0")
right_mag_fail = dref.getDataref("sim/operation/failures/rel_magRGT0")
cooling_crackling = dref.newInt("ujs/control/cooling_crackling")
---------------------------------------------------------------------------------ON JACKS
xdr_override_planepath = dref.getDataref("sim/operation/override/override_planepath")
override_planepath = dref.getIntV(xdr_override_planepath, 1, 1)
on_jacks = dref.newInt("ujs/control/on_jacks")
theta_pitch = dref.getDataref("sim/flightmodel/position/theta")
local_y = dref.getDataref("sim/flightmodel/position/local_y")
can_local_y = dref.newInt("ujs/control/can_local_y")

--USE THIS FOR THE JACKS!!! 	sim/operation/override/override_planepath
lgear_remove_smooth = dref.newFloat("ujs/control/lgear_remove_smooth")
lgear_remove = dref.newInt("ujs/control/lgear_remove")
rgear_remove = dref.newInt("ujs/control/rgear_remove")
rgear_remove_smooth = dref.newFloat("ujs/control/rgear_remove_smooth")
tire_fail1 = dref.getDataref("sim/operation/failures/rel_tire1")
tire_fail2 = dref.getDataref("sim/operation/failures/rel_tire2")
tire_fail3 = dref.getDataref("sim/operation/failures/rel_tire3")
tire_fail4 = dref.getDataref("sim/operation/failures/rel_tire4")
tire_fail5 = dref.getDataref("sim/operation/failures/rel_tire5")

rlanding_count = dref.newInt("ujs/control/rlanding_count")
llanding_count = dref.newInt("ujs/control/llanding_count")
landed = dref.newInt("ujs/control/landed")
ltire_condition = dref.newInt("ujs/control/ltire_condition")
rtire_condition = dref.newInt("ujs/control/rtire_condition")
ltire_burst = dref.newInt("ujs/control/ltire_burst")
rtire_burst = dref.newInt("ujs/control/rtire_burst")
xdr_idle_speed_ratio = dref.getDataref("sim/cockpit2/engine/actuators/idle_speed_ratio")
--idle_speed_ratio = dref.getFloatV(xdr_idle_speed_ratio, 1, 1)
lfuel_cap = dref.newInt("ujs/control/lfuel_cap")
rfuel_cap = dref.newInt("ujs/control/rfuel_cap")
lfuel_cap_smooth = dref.newFloat("ujs/control/lfuel_cap_smooth")
rfuel_cap_smooth = dref.newFloat("ujs/control/rfuel_cap_smooth")
lfuel_pouring = dref.newInt("ujs/control/lfuel_pouring")
rfuel_pouring = dref.newInt("ujs/control/rfuel_pouring")
lfuel_pouring_smooth = dref.newFloat("ujs/control/lfuel_pouring_smooth")
rfuel_pouring_smooth = dref.newFloat("ujs/control/rfuel_pouring_smooth")
lfuel_qty = dref.getDataref("sim/flightmodel/weight/m_fuel1")
rfuel_qty = dref.getDataref("sim/flightmodel/weight/m_fuel2")
tailwheel_inspection = dref.newInt("ujs/control/tailwheel_inspection")
tailwheel_modded = dref.newInt("ujs/control/tailwheel_modded")
tires_status = dref.newInt("ujs/control/tires_status")
latitude = dref.getDataref("sim/flightmodel/position/latitude")
show_ipad = dref.newInt("ujs/control/show_ipad")
--avi_enabled = dref.newInt("avitab/panel_enabled")
--avi_powered = dref.newInt("avitab/panel_powered")


--]]

--Bugs!
bg1 = dref.newInt("ujs/control/bg1")
bg2 = dref.newInt("ujs/control/bg2")
bg3 = dref.newInt("ujs/control/bg3")
bg4 = dref.newInt("ujs/control/bg4")
bg5 = dref.newInt("ujs/control/bg5")
bg6 = dref.newInt("ujs/control/bg6")
bg7 = dref.newInt("ujs/control/bg7")
bg8 = dref.newInt("ujs/control/bg8")
bg9 = dref.newInt("ujs/control/bg9")
bg10 = dref.newInt("ujs/control/bg10")
bg11 = dref.newInt("ujs/control/bg11")
bg12 = dref.newInt("ujs/control/bg12")
bugged = dref.newInt("ujs/control/bugged")

--Optimization
smokey_killer = dref.newInt("ujs/control/smokey_killer")
dref.setInt(smokey_killer, 1)
--SOUNDS
idle_rpm = dref.newInt("ujs/control/idle_rpm")
startup = dref.newInt("ujs/control/startup")
acf_roll = dref.getDataref("sim/flightmodel/position/true_phi")
acf_coughing = dref.newInt("ujs/control/cough")
xdr_tires_rolling = dref.getDataref("sim/flightmodel2/gear/tire_rotation_speed_rad_sec")
tires_rolling = dref.getFloatV(xdr_tires_rolling, 2, 1)
we_rolling = dref.newInt("ujs/control/we_rolling")
we_graveling = dref.newInt("ujs/control/graveling")
rattling_hard = dref.newInt("ujs/control/rattling_hard")
rattling_easy = dref.newInt("ujs/control/rattling_easy")
xdr_on_noisy = dref.getDataref("sim/flightmodel2/gear/on_noisy")
on_noisy = dref.getIntV(xdr_on_noisy, 2, 1)
--skidding = globalPropertyfa("sim/flightmodel2/gear/tire_skid_speed_mtr_sec")
ouch = dref.newInt("ujs/control/ouch")
panel_vibration = dref.newFloat("ujs/control/panel_vibration")
please_vibrate = dref.newInt("ujs/control/please_vibrate")
hardcore_vibration = dref.newInt("ujs/control/hardcore_vibration")
vibration_peak = dref.newInt("ujs/control/vibration_peak")
touchdown_vibrate = dref.newInt("ujs/control/touchdown_vibrate")
touchdown_timer = dref.newFloat("ujs/control/touchdown__timer")
cube_prep_mode = dref.getDataref("sim/private/controls/render/cube_prep_mode")
--
dref.setInt(bat_on, 1)
dref.setFloatV(xdr_mixture_ratio, 1, 0)
dref.setInt(has_stall, 1)
dref.setFloat(high_idle, 1.3)
dref.setFloat(low_idle, 0.8)
dref.setFloat(cube_prep_mode, 2)
